### ISSUE TITLE
None of the language packs work

### ISSUE THREAD

**Issue by tarekis** [madskristensen/TextmateBundleInstaller#10]
I've installed the plugin, and the bundles are just unused, is there some fancy way to install this, which is not documented, or could there be anything that just blocks the bundles?

**Comment by madskristensen** [comment]
Do you have Visual Studio 2015 Update 2 or newer? I'm wondering if the Textmate support didn't work properly until Update 3 perhaps

**Comment by tarekis** [comment]
I have Visual Studio 14.something, can't look it up right now; but it's most definetely Update 3. Might it be because i use Node-Js-Tools? VS uses it's .njsproj-Project File and a .sln-Project File, might collide, no idea tho.

**Comment by madskristensen** [comment]
It should not have any impact that you are using NTVS at all. Can you please try the latest [CI build](http://vsixgallery.com/extension/4773ce75-6f30-4269-9557-1f7c30a47be2/) and see if it works there? You may have to restart VS a couple of times

**Comment by madskristensen** [comment]
This has now been fixed in the latest [CI build](http://vsixgallery.com/extension/4773ce75-6f30-4269-9557-1f7c30a47be2/)
