### ISSUE TITLE
Missing support for .atg files

### ISSUE THREAD

**Issue by maggarwal** [madskristensen/TextmateBundleInstaller#101]
Thanks for adding the icon. Would be great to have syntax highlighting for atg files as well.

Maybe following will help

https://packagecontrol.io/packages/Coco%20R%20Syntax%20Highlighting

**Comment by maggarwal** [comment]
I think following repo has textmate files for the language

https://github.com/mschoebel/cocosyntax

**Comment by maggarwal** [comment]
New version doesn't fix this. Still not syntax highlighting.

**Comment by madskristensen** [comment]
I see this:

![image](https://cloud.githubusercontent.com/assets/1258877/20807134/84876776-b7b2-11e6-92ba-0fdacfb33046.png)

when I use this code:

```
static bool FollowsB () {
  Scanner.StartPeek();
  int peek = la.kind;
  // look behind { a }
  while (peek == Tokens.a)
    peek = Scanner.Peek().kind;
  return peek == Tokens.b;
}
```

**Comment by maggarwal** [comment]
Well, it just started work magically just now. Maybe needed some time to sink in ;)

**Comment by madskristensen** [comment]
Yes, it sometimes needs a little time or a restart to fully be enabled. I'm not sure why that is, but expect it has to do with the VS cache of textmate bundles
