### ISSUE TITLE
asm highlight in .c (and .cpp? I dont know it work in cpp or no, but in C it work) in __asm{}

### ISSUE THREAD

**Issue by nibytes** [madskristensen/TextmateBundleInstaller#114]
![default](https://cloud.githubusercontent.com/assets/15169344/20743080/d3325128-b6dc-11e6-8fed-8fae2a4b9b7a.png)

**Comment by nibytes** [comment]
Аnd one question, you add .asm highlight recently, when it is available in VS, I'am delete Syntax Highlighting Pack and reinstall from gallery, but asm is not available.

**Comment by madskristensen** [comment]
I'm probably releasing it later this week or next week. In the mean time, grab the CI build from here http://vsixgallery.com/extension/4773ce75-6f30-4269-9557-1f7c30a47be2/

**Comment by madskristensen** [comment]
It has now been released

**Comment by nibytes** [comment]
thx
