### ISSUE TITLE
Missing support for .tick files

### ISSUE THREAD

**Issue by jakobnotseth** [madskristensen/TextmateBundleInstaller#115]
Kapacitor scripts
https://docs.influxdata.com/kapacitor/latest/
https://github.com/influxdb/kapacitor

**Comment by madskristensen** [comment]
I can't find any Textmate bundles for .tick files. Do you know of any

**Comment by madskristensen** [comment]
I found one :)

**Comment by jakobnotseth** [comment]
Sorry for the late reply, it's GO-syntax if I understand it correctly :)
