### ISSUE TITLE
Missing support for .htaccess files

### ISSUE THREAD

**Issue by davidlmorris** [madskristensen/TextmateBundleInstaller#12]

**Comment by madskristensen** [comment]
The file type is supported by this extension

![image](https://cloud.githubusercontent.com/assets/1258877/18675952/d8ad7aa8-7f08-11e6-83c9-e2c5437a2f8d.png)

Try restarting VS if the colors don't show up

**Comment by davidlmorris** [comment]
I auto reported this via (I assume) your extension.  Which BTW is a cool addition (like many others).  I am using an external NODE,JS, and am running much of my tooling via that rather than other tools (e.g. GULP, LESS et al), in case this is relevant.  But perhaps I'm expecting more than I should? This image from after a cold start of the PC this morning.  Icons extension works. (Message popped up again too).  
![vs_htaccess_icon](https://cloud.githubusercontent.com/assets/20590543/18692670/a6831300-7fce-11e6-8f6e-6eedf2dd2b09.png)
![htaccess](https://cloud.githubusercontent.com/assets/20590543/18692679/af56b02c-7fce-11e6-8d84-9eb5490adbc0.png)

**Comment by davidlmorris** [comment]
I've just run the update for the update 3... and that has resolved the issue.  Apologies for time wasting.
