### ISSUE TITLE
Missing support for .scm files

### ISSUE THREAD

**Issue by piyushsoni** [madskristensen/TextmateBundleInstaller#121]
Hi, it's written on the extension home page that Scheme files are supported. Then why don't I see .scm (Scheme) files syntax highlighted? 

This is the language URL : https://www.gnu.org/software/mit-scheme/

**Comment by madskristensen** [comment]
It has been added

**Comment by piyushsoni** [comment]
Hi,
Thanks! I don't know if you did something (looks like it was already there), but I see the syntax highlighting now in VS 2017 (it didn't work as soon as I installed the extension and restarted it).
