### ISSUE TITLE
Missing support for .yml files

### ISSUE THREAD

**Issue by dustinmoris** [madskristensen/TextmateBundleInstaller#127]
The title says it all :)

**Comment by madskristensen** [comment]
This is included

**Comment by dustinmoris** [comment]
Doesn't work for me though :/

**Comment by laedit** [comment]
Seems that it doesn't work on Visual Studio 2017, even with the extension installed.
![syntaxhighlightingpack_yml](https://cloud.githubusercontent.com/assets/871092/23797828/05df3e6a-05a2-11e7-8ee8-e1e7f0f40171.png)
