### ISSUE TITLE
Missing support for .properties files

### ISSUE THREAD

**Issue by twurm** [madskristensen/TextmateBundleInstaller#130]
Generally these are Java files, however we use them in VS for SonarQube.

https://docs.oracle.com/cd/E23095_01/Platform.93/ATGProgGuide/html/s0204propertiesfileformat01.html

**Comment by madskristensen** [comment]
I can't find a textmate bundle for this file type. Can you?

**Comment by twurm** [comment]
It looks like its part of the java bundle.  [textmate Java bundle](https://github.com/textmate/java.tmbundle/tree/master/Preferences)

**Comment by madskristensen** [comment]
Perfect, thanks for finding the file. It works great

**Comment by twurm** [comment]
Thanks Mads!
