### ISSUE TITLE
Missing support for .pl files

### ISSUE THREAD

**Issue by romanwue** [madskristensen/TextmateBundleInstaller#14]
Optionally, please give more details such as language name and homepage URL

**Comment by madskristensen** [comment]
.pl file support is included in this extension. You may have to restart VS before it kicks in. You can see what textmate bundles was installed by looking in the %userprofile%\.vs\Extensions folder.

Here's what I get when opening a .pl file:

![image](https://cloud.githubusercontent.com/assets/1258877/18676014/1cf29d06-7f09-11e6-910e-bb41be64b3ce.png)
