### ISSUE TITLE
Crash/hang on .tpl files

### ISSUE THREAD

**Issue by RobThree** [madskristensen/TextmateBundleInstaller#144]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: Syntax Highlighting Pack 2.2.95
- May be relevant: [PHP Tools for VS](https://www.devsense.com/) 1.21.9350

### Description
Visual Studio crashes or hangs (reproducibly) when opening ([Smarty](http://www.smarty.net/)) `.tpl` files.

### Steps to recreate
1. Double-click a `.tpl` file in the solution explorer
2. Wait a few seconds
3. Visual Studio window title changes to "... not responding" and VS needs to be shut down / quit by killing it in the task explorer *or* it crashes (50/50)

### Current behavior
Crashing / hang

### Expected behavior
Not crash / hang

After I disable the Syntax Highlighting Pack extension I can open `.tpl` files fine.

**Comment by madskristensen** [comment]
If you disable PHP Tools extension does it then work. Uninstalling the Syntax Highlighting Pack still leaves behind the files that VS use to syntax highlight with, so it should have no impact at all if you uninstall this extension which makes me believe it is something else

**Comment by madskristensen** [comment]
Actually, the Smarty support this extension brings is that it maps .tlp files to the HTML editor and that is it. Without the extension a .TPL file might open as plain text. Can you open another instance of VS and attach the debugger to get a stack trace, please?

**Comment by RobThree** [comment]
I'll try but it'll have to wait until tomorrow since it happens at work and I'm off now 😉 
What you're saying does make sense though and I didn't get around to trying without PHP Tools (or with PHP Tools disabled).

**Comment by madskristensen** [comment]
@RobThree Any update?

**Comment by RobThree** [comment]
No sorry, no update yet. Been (too) busy. But tomorrow is my last day of work (for this year that is 😉 ) so I'll try to test it more thoroughly then.

**Comment by RobThree** [comment]
I'm afraid the problem is somewhere else... I have disabled both and it still occurs (but not as reliably...). I'll investigate further and keep you posted...
