### ISSUE TITLE
Missing support for .sh or .bash files

### ISSUE THREAD

**Issue by AlbinoGeek** [madskristensen/TextmateBundleInstaller#146]
Doesn't seem to support any shell scripting...

**Comment by madskristensen** [comment]
You may have to restart VS for it to work. Here's what it looks like on my machine:

![image](https://cloud.githubusercontent.com/assets/1258877/21322713/281ca71e-c5cf-11e6-9bd3-cf7ea518c833.png)

**Comment by jgwinner** [comment]
Something is missing - I have the same problem; all I did on a fairly fresh  machine was install this extension. I've restarted VS a few times.

Do I have to install something separately? If so, the readme needs updating.

I'm in dark mode.

Does it work in VS 2019?

Seems like some others have had the same issue.
