### ISSUE TITLE
Missing support for bash script file without extension

### ISSUE THREAD

**Issue by aleksey-nikolaev** [madskristensen/TextmateBundleInstaller#15]
### Installed product versions
- MICROSOFT VISUAL STUDIO ENTERPRISE 2015
- This extension: Syntax Highlighting Pack   1.2.17

### Description
Very good Pack. But. Is it possible recognise bash syntax for files without extensions?

I have a lot of script files without extensions, but Syntax Haghlighting Pack ignores them. 

#!/bin/bash in the first line allows you to determine that it was a bash script

**Comment by madskristensen** [comment]
Unfortunately, the way the textmate bundles work in VS is by file extension only and there is no way to instruct it to behave differently - no API to use for it.
