### ISSUE TITLE
Missing support for .cmd files

### ISSUE THREAD

**Issue by mhulth** [madskristensen/TextmateBundleInstaller#152]
Simply an updated version of a Microsoft batch file (*.bat). Not sure if .bat files are supported as I only use .cmd files, but they should be treated as one and the same if they are.

https://en.wikipedia.org/wiki/Batch_file#Filename_extensions

**Comment by madskristensen** [comment]
.cmd files are supported. Try to restart VS and open a .cmd file again to see if it works. Sometimes VS has to be restarted after first installing this extension in order for it to register all the new textmate bundles
