### ISSUE TITLE
Missing support for .qwc files

### ISSUE THREAD

**Issue by jcampbell-gists** [madskristensen/TextmateBundleInstaller#153]
Optionally, please give more details such as language name and homepage URL

**Comment by madskristensen** [comment]
Is this a QuickBooks file?

**Comment by jcampbell-gists** [comment]
Hey good afternoon,

Yes this is a quickbooks file specifically an xml based file used by quickbooks web connector to locate a hosted webservice to facilitate communitication to quickbooks desktop.

I hope this information helped out.



On Tue, Jan 3, 2017 at 2:34 PM -0500, "Mads Kristensen" <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this a QuickBooks file?

**Comment by madskristensen** [comment]
I can't find a Textmate bundle for this file type. Do you know of any?

**Comment by madskristensen** [comment]
Wait, are .qwc files just XML files? I can map .qwc to always open in the XML editor if that helps?

**Comment by jcampbell-gists** [comment]
From what I can see yes they are, they have specific elements but there is no namespace to validate against. If possible you can look into http://developer.intuit.com/docs under the desktop section the docs there can she's more light on how best to support .qwc files

I'm just recently making sense of the framework myself so sorry I'm a bit lacking in the details.



On Tue, Jan 3, 2017 at 5:04 PM -0500, "Mads Kristensen" <notifications@github.com<mailto:notifications@github.com>> wrote:


Wait, are .qwc files just XML files? I can map .qwc to always open in the XML editor if that helps?
