### ISSUE TITLE
What is the Antlr support expected to do

### ISSUE THREAD

**Issue by RobertvanderHulst** [madskristensen/TextmateBundleInstaller#158]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 2.3.100

### Description
What is the Antlr support expected to do ?
I see almost everything as Comment.

### Current behavior
Everything looks in comment color

### Expected behavior
I would expect some different colors for rules, Lexer tokens, operators etc.
It think is related to // comments. These somehow are interpreted like multi line comments.

**Comment by madskristensen** [comment]
There seem to be an issue with `//` comments. The workaround for now is to use `/* ... */` syntax comments instead. Please open an issue on the [Textmate bundle repo](https://github.com/iuliux/SublimeText2-Antlr-syntax) for Antlr
