### ISSUE TITLE
Missing support for QT files: .pro, .pri, .prf, .qml, .qrc

### ISSUE THREAD

**Issue by aleksey-nikolaev** [madskristensen/TextmateBundleInstaller#16]
### Installed product versions
- MICROSOFT VISUAL STUDIO ENTERPRISE 2015
- This extension: Syntax Highlighting Pack 1.2.17

It would be great to be able to edit the QT project files with syntax highlighting, not only in qtcreator

**Comment by madskristensen** [comment]
Here's what it looks like:

![image](https://cloud.githubusercontent.com/assets/1258877/18676457/80c6e642-7f0a-11e6-8bdc-750f7f0bdf65.png)

Grab the latest [CI build](http://vsixgallery.com/extension/4773ce75-6f30-4269-9557-1f7c30a47be2/) to test it out. It works with .pro and .pri files.
