### ISSUE TITLE
Intellisense for comments

### ISSUE THREAD

**Issue by aleksey-nikolaev** [madskristensen/TextmateBundleInstaller#17]
### Installed product versions
- This extension: Syntax Highlighting Pack 1.2.17

Could you add detection comments to be able to use the command: comment out a line or selection (Ctrl+K or Ctrl+C)

**Comment by madskristensen** [comment]
The *Commands* part of Textmate bundles are not supported by VS, unfortunately. I guess I could add that manually through the editor APIs though
