### ISSUE TITLE
Missing support for .csh files

### ISSUE THREAD

**Issue by jbhurst** [madskristensen/TextmateBundleInstaller#180]
Maybe this is a better way to post this than my previous issue asking how to change an existing bundle.  I'd like to see support for CShell .csh files.  

In my case, I'd also like to apply the formatting to .rc, .pre, and .post files, but that isn't necessarily standard.  

The existing tcl or shellscript bundles should work for my purposes.

There is another csh/tcsh bundle here: https://github.com/supergra/tcsh-sublime that claims to work better for csh if you want to include it.  I couldn't figure out how to make it work with VS 2015.

Thanks for the very helpful VS extension.

**Comment by jbhurst** [comment]
Is there a way to see in VS 2015 which TMBundle is being used to render the file?  Perhaps there is a conflict with multiple bundles supporting the extension?

**Comment by jbhurst** [comment]
I'm becoming convinced that VS is pre-empting the TextMate filters from kicking in with some sort of preset formatting for csh.  I found some files here, for example, that seem to reference .csh, but changing them didn't help.  
\MicrosoftVisualStudio14.0\Common7\IDE\CommonExtensions\Microsoft\VC\VC_Pkg_Core_Registration.pkgdef

**Comment by madskristensen** [comment]
I'll take a look shortly

**Comment by madskristensen** [comment]
That sublime bundle doesn't work in VS for some reason

**Comment by madskristensen** [comment]
I've added the file extensions .tsch, .rc, .pre and .post to the TCL bundle, but I can't add .sch because that file extension is taken by the Scheme language

**Comment by madskristensen** [comment]
Doh! I  spelled it wrong. It's .csh and not .sch :)

**Comment by madskristensen** [comment]
Ok, I've committed the changes. One caveat, if you have the C++ editor installed in VS then it will take over handling .csh files, but not the other file extensions

**Comment by madskristensen** [comment]
You can verify it works by getting the [CI build](http://vsixgallery.com/extension/4773ce75-6f30-4269-9557-1f7c30a47be2/)

**Comment by jbhurst** [comment]
Thanks so much - so you were able to work around the Scheme conflict, or do I need to do something there?  Not using C++, just # and VB.  I'll try the CI build.

**Comment by madskristensen** [comment]
The Scheme conflict didn't exist afterall. The conflict exist for .csh files being opened by the C++ editor instead of the textmate bundle. The other file extensions you listed should work just fine

**Comment by jbhurst** [comment]
Yeah, the c++ editor is still grabbing it.  Do you know of a way to disable that since I don't use C++?

**Comment by madskristensen** [comment]
I don’t. I’ve looked into it before and couldn’t figure it out. I can ask around

**Comment by jbhurst** [comment]
Ok - I have a case with MS I can use I think, maybe I'll try that.  If you
send me your e-mail/paypal to brady dot hurst at gmail dot com, I'd like to
send that donation for your efforts.

**Comment by madskristensen** [comment]
I appreciate your offer, but I wouldn't charge for this. It's my job so someone is already paying me for it :)

**Comment by jbhurst** [comment]
Ah ok, I thought it was a hobby project.  I'll let you know if I hear anything from MS.

**Comment by jbhurst** [comment]
Just realized you work for MS.  Here is the forum post for it if you know any co-workers that might be able to help.  https://social.msdn.microsoft.com/Forums/vstudio/en-US/f75af854-5829-4c0f-8692-a86fa53aa844/csh-extension-c-association-change?forum=vssetup
