### ISSUE TITLE
(prompted by VS2017 extension) Missing support for paket.* files

### ISSUE THREAD

**Issue by tebeco** [madskristensen/TextmateBundleInstaller#193]
When opening "paket" files such as :
* paket.dependencies
* paket.lock
* paket.local
* paket.references

It seems that the templating extension prompt me to submit an issue here in order to support these "textmate template" so here I am

The format is ... plain text based on few reserved keyword and might or not be indented (expect some the lock file)

I'm not even sure of the rules but at least it's "in the backlog" somewhere now :)

**Comment by madskristensen** [comment]
VS cannot map textmate bundles to files containing certain chars in the name. Only file extensions. So unfortunately this cannot be done
