### ISSUE TITLE
Missing detection of some QT variables

### ISSUE THREAD

**Issue by aleksey-nikolaev** [madskristensen/TextmateBundleInstaller#20]
### Installed product versions
- MICROSOFT VISUAL STUDIO ENTERPRISE 2015
- This extension: Syntax Highlighting Pack 1.3.32

### Description
PKGCONFIG was not detected 
![image](https://cloud.githubusercontent.com/assets/12497264/18706722/c7f84bd6-7ffb-11e6-8279-1f967c50f5e6.png)

Must be like that (QTcreator)
![image](https://cloud.githubusercontent.com/assets/12497264/18706573/43507520-7ffb-11e6-8307-5e9bed8c23cb.png)
You can find all variables and functions in the qt documentation
http://doc.qt.io/qt-5/qmake-variable-reference.html
http://doc.qt.io/qt-5/qmake-function-reference.html
http://doc.qt.io/qt-5/qmake-test-function-reference.html

**Comment by madskristensen** [comment]
Please open the bug on the textmate bundle repo here https://github.com/textmate/cpp-qt.tmbundle
