### ISSUE TITLE
Uninstalling the extension doesn't clear the users's .vs/Extensions folder

### ISSUE THREAD

**Issue by Tragetaschen** [madskristensen/TextmateBundleInstaller#218]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 2.5.113

### Description
When I uninstall the extension, the entire users's `.vs/Extensions` folder remains active.

### Steps to recreate
1. Install the extension
2. Start VS 2017
3. Note the user's `.vs/Extensions` folder was created
4. Uninstall the extension
5. The entire folder and its contents remain active and used by VS

### Current behavior
The syntax files remain active

### Expected behavior
The syntax files shouldn't remain active

See also https://github.com/Microsoft/TypeScript/issues/14422

**Comment by madskristensen** [comment]
Thanks for reporting this. It has been fixed in version 2.7
