### ISSUE TITLE
Does not detect variables after \ in .pr* QT-files

### ISSUE THREAD

**Issue by aleksey-nikolaev** [madskristensen/TextmateBundleInstaller#22]
### Installed product versions
- MICROSOFT VISUAL STUDIO ENTERPRISE 2015
- This extension: Syntax Highlighting Pack 1.3.32

### Description
Does not detect variables after `\`
![msvc](https://cloud.githubusercontent.com/assets/12497264/18706884/6b4a12d8-7ffc-11e6-938d-234724334ad5.png)

Must be like that (qt creator):
![qt creator](https://cloud.githubusercontent.com/assets/12497264/18706978/ba12d31e-7ffc-11e6-98a6-d06037a5fd69.png)

**Comment by madskristensen** [comment]
Please open the issue on the textmate bundle repo here https://github.com/textmate/cpp-qt.tmbundle
