### ISSUE TITLE
Missing support for QT (qml) files: .qml, .qrc

### ISSUE THREAD

**Issue by aleksey-nikolaev** [madskristensen/TextmateBundleInstaller#23]
### Installed product versions
- MICROSOFT VISUAL STUDIO ENTERPRISE 2015
- This extension: Syntax Highlighting Pack 1.3.32
### Description

This may help:
http://doc.qt.io/qt-5/qmlbasictypes.html

For example
![image](https://cloud.githubusercontent.com/assets/12497264/18707697/f40ca934-7fff-11e6-8fc8-5c3e1f000d40.png)

**Comment by madskristensen** [comment]
Is that the same as .pro and .pri files?

**Comment by aleksey-nikolaev** [comment]
No, not the same. They looks like JavaScript

**Comment by madskristensen** [comment]
I can't find a textmate bundle for qml files. Do you know of one?

**Comment by KindDragon** [comment]
https://github.com/bbenoist/vscode-qml

**Comment by madskristensen** [comment]
@KindDragon Perfect, thanks so much 👍

**Comment by KindDragon** [comment]
@madskristensen He uses the MIT license, you forgot to add it

**Comment by madskristensen** [comment]
Good call. Thanks
