### ISSUE TITLE
Missing support for .proto files

### ISSUE THREAD

**Issue by jmatter** [madskristensen/TextmateBundleInstaller#241]
Google Protocol Buffers
https://developers.google.com/protocol-buffers/

**Comment by breyed** [comment]
Protocol Buffers 2 is supported. However, Protocol Buffers 3 is not. For example, consider this code:

```
message MyMessage {
	string first_field = 1;
	repeated string second_field = 2;
}
```

The keyword `string` is only highlighted for second_field because its syntax is valid in Protocol Buffers 2, whereas the first_field is only valid in Protocol Buffers 3.
