### ISSUE TITLE
[suggestion] Add "force use this extension for file type" setting.

### ISSUE THREAD

**Issue by zldrq** [madskristensen/TextmateBundleInstaller#29]
### Installed product versions
- Visual Studio: 2015 ent, upd 3
- This extension: latest (built from this repo)

### Description

I can't get your beautiful extension to work on my working instance of VS, but it works on experimental instance (when i build your extension from this repo and run it).
Obviously, some extension or somewhat is interfering (and, as you say, your extension has lowest priority).
I've tried like 5-7 file types with no positive results. there is no highlighting in any of them and I seemingly have nothing installed to be used for those types.
I've switched off all extensions that may theoretically interfere, but no result also.

While I understand it's my "fault", I will dare to suggest couple of features:
* in settings dialog: add list of supported file types with checkboxes. Checkboxes will mean "force this". So your extension will be low priority for those extensions, which are unchecked and top priority for those are checked.
* or/and add "debug mode", which will log, "who" is in control of highlighting for particular file type. (or please direct me where to search it, so i figure out myself)

thanks, and sorry if this type of request must not belong here (tho, I suppose it confirms with the guidelines)

**Comment by madskristensen** [comment]
Unfortuantely, this cannot be done since the native textmate bundle support in VS2015 doesn't support it

**Comment by madskristensen** [comment]
There is not AFAIK a way to show that.
