### ISSUE TITLE
Missing support for .pl files

### ISSUE THREAD

**Issue by Mordef** [madskristensen/TextmateBundleInstaller#3]
Optionally, please give more details such as language name and homepage URL
Perl https://www.perl.org/

**Comment by madskristensen** [comment]
Perl should already be supported. I just created a .pl file and here's what it looks like:

![image](https://cloud.githubusercontent.com/assets/1258877/18354831/e554cba6-759b-11e6-9305-278f8a10d0a0.png)

Do you get colorization for Perl now?

**Comment by Mordef** [comment]
No, i got the message to report missing files

**Comment by madskristensen** [comment]
Can I get you to try the latest [CI build](http://vsixgallery.com/extension/4773ce75-6f30-4269-9557-1f7c30a47be2/) and see if that fixes the issue? You may have to close and open the .pl file once just the first time.

Also, can you check if you've got a folder named *perl* in `%userprofile%\.vs\Extensions` before and after you try the CI build, please?

**Comment by Mordef** [comment]
Before there where no Perl Folder, after the new Build i have it, but it still not work:
In he folder i have 2 more folders with files:
- Snippets
- Syntaxes 

But still not working:

![lastci](https://cloud.githubusercontent.com/assets/22061464/18440005/c45de954-7907-11e6-87ea-c2f9ec3afa1d.PNG)

**Comment by madskristensen** [comment]
Please install VS2015 Update 3 and the latest version of this extension if it still doesn't work

**Comment by madskristensen** [comment]
Fixed in latest CI build
