### ISSUE TITLE
Wrong comment out the selected lines

### ISSUE THREAD

**Issue by aleksey-nikolaev** [madskristensen/TextmateBundleInstaller#36]
### Installed product versions
- Visual Studio: ENTERPRISE 2015
- This extension:  1.5.42

### Description
Commenting of one line work perfect. Multiple lines  does not commented - only first line in the selection.

### Steps to recreate
Take a simle text
```
1 not selected line
2 line for comment
3 selected for comment
4 must not to be selected
```
Select some line. (Mouse above line numbers (6 line), push LMB, move  mouse down for select two lines, release LMB)
![image](https://cloud.githubusercontent.com/assets/12497264/19189429/a9a465d2-8ca0-11e6-8660-593253ce4ccf.png)
Push the "Comment out the selected lines" button (Ctrl+k, Ctrl+o)
![image](https://cloud.githubusercontent.com/assets/12497264/19189163/fd3b4dfc-8c9e-11e6-847c-0aa5ad14955f.png)

### Current behavior
1. Only line 2... was commented.
2. Line 4... was selected too.

### Expected behavior
After  "comment out the selected lines" selection shuold not expand to next line. 
All lines in the selection shuold be commented.

**Comment by madskristensen** [comment]
"Comment out selected lines (Ctrl+K, Ctrl+o)" is not a Visual Studio command. Is it perhaps ReSharper? If you use the Visual Studio commands for commenting (Ctrl+K, Ctrl+C) it should work fine.

**Comment by madskristensen** [comment]
There was actually a bug in the comment code and I'm fixing it now. I stil don't know where the "Comment out selected lines" command you are using comes from though

**Comment by aleksey-nikolaev** [comment]
I  am sorry 
![image](https://cloud.githubusercontent.com/assets/12497264/19197809/9163f572-8cc4-11e6-986a-20c63380e1a5.png)
Ctrl+K, Ctrl+C of course
