### ISSUE TITLE
Select the syntax from the context menu

### ISSUE THREAD

**Issue by aleksey-nikolaev** [madskristensen/TextmateBundleInstaller#37]
### Installed product versions
- This extension: 1.5.42

### Description
This should be very useful if you can apply the syntax to the  ile with unknown extension or without extension. Easy way when I can choose a syntax from the context menu.
You may also remember my choice for the current file
Is API enough for this?
#15

**Comment by madskristensen** [comment]
Unfortunately, this is not possible since VS doesn't allow for this when dealing with Textmate bundles.

/cc @markw-t
