### ISSUE TITLE
Missing support for .tpl files

### ISSUE THREAD

**Issue by Mordef** [madskristensen/TextmateBundleInstaller#4]
Smarty
http://www.smarty.net/

**Comment by madskristensen** [comment]
Should .TPL files perhaps just be associated with the HTML editor?

**Comment by madskristensen** [comment]
For some reason the smarty textmate bundle doesn't work in VS. Very strange

**Comment by Mordef** [comment]
Oh bad.
tpl i can assign html with code, but thats not smarty.
Atm i use differnt editor for Smarty files where i have highlighting

**Comment by madskristensen** [comment]
Closing since I can't do anything about it. I've mapped smarty file extensions to open in the HTML editor which does give some syntax highlighting to smarty syntax
