### ISSUE TITLE
Missing support for GLSL .frag, .vert, .geom files

### ISSUE THREAD

**Issue by akaltar** [madskristensen/TextmateBundleInstaller#40]
GLSL fragment shader and vertex shader files. Its a C derivative with a lot of builtins.

There are other files following the same scheme with minor differences for tesselation control shader, tesselation shader, compute shader

If you would just add a quick fix treating them as C, it would be nice too. supporting builtins would  be ideal.

**Comment by madskristensen** [comment]
The textmate bundle for GLSL can't work because it uses `<include>` syntax which isn't supported by VS. I've mapped the file types to the C editor instead.
