### ISSUE TITLE
Missing support for .pdf files

### ISSUE THREAD

**Issue by spakh** [madskristensen/TextmateBundleInstaller#51]
Optionally, please give more details such as language name and homepage URL

I suppose registering a PDF reader with Visual Studio and setting it as the default program to execute when double clicking a .pdf file is simple enough. I was just expecting VS to auto discover the PDF reader I have installed (Foxit Reader or Adobe Reader, etc) and use it without having to do all the registration stuff. heh. :)

**Comment by madskristensen** [comment]
This is unfortunately out of scope of this extension. It is a completely different feature set required than working with textmate bundles, which is the only thing this extension does. You can do it manually by right-clicking the file and register an .exe to handle the .pdf file extension for you
