### ISSUE TITLE
Missing support for .y files

### ISSUE THREAD

**Issue by manar-alkull** [madskristensen/TextmateBundleInstaller#61]
Optionally, please give more details such as language name and homepage URL

**Comment by madskristensen** [comment]
What language is that?

**Comment by madskristensen** [comment]
The [Bison textmate bundle](https://github.com/textmate/bison.tmbundle) isn't compatible with VS. This is unfortunate

**Comment by GitMensch** [comment]
Why isn't it compatible? Is the same true for https://github.com/textmate/lex-flex.tmbundle?

Can it be made compatible?
