### ISSUE TITLE
Missing support for .htaccess files

### ISSUE THREAD

**Issue by Gastror** [madskristensen/TextmateBundleInstaller#62]
Seems clear enough to me, right?

**Comment by madskristensen** [comment]
I get basic syntax highlighting for .htaccess files in the latest version.

![image](https://cloud.githubusercontent.com/assets/1258877/19839425/97b6486c-9e9e-11e6-97a5-06e9f1a3a39d.png)

Do you have the latest version installed?

**Comment by Gastror** [comment]
I do now, thank you for pointing that out.
