### ISSUE TITLE
Missing support for .sqlce files

### ISSUE THREAD

**Issue by berny900** [madskristensen/TextmateBundleInstaller#67]
SQL Server Compact

**Comment by madskristensen** [comment]
Is this a SQL text file just like .sql files?

**Comment by berny900** [comment]
Yes,

 

sample:

 

-- Script Date: 02.12.2015 17:59  - ErikEJ.SqlCeScripting version 3.5.2.56

SELECT [SalesHistoryId]

      ,[SalesDate]

      ,[AgentId]

      ,a.Lastname AS AgentName

      ,[BuyerId]

      ,b.Lastname AS BuyerName

      ,[SellerId]

      ,seller.Lastname AS SellerName

      ,[RealEstateId]

  FROM [SalesHistory] s join People a on s.agentid = a.businessentityid

  join People b on s.buyerid = b.businessentityid

  join People seller on s.SellerId = seller.businessentityid;

GO

 

Regards

 

Berni

 

Von: Mads Kristensen [mailto:notifications@github.com] 
Gesendet: Mittwoch, 2. November 2016 16:56
An: madskristensen/TextmateBundleInstaller
Cc: berny900; Author
Betreff: Re: [madskristensen/TextmateBundleInstaller] Missing support for .sqlce files (#67)

 

Is this a SQL text file just like .sql files?

**Comment by berny900** [comment]
Thanks

 

Berni

 

Von: Mads Kristensen [mailto:notifications@github.com] 
Gesendet: Mittwoch, 2. November 2016 20:56
An: madskristensen/TextmateBundleInstaller
Cc: berny900; Author
Betreff: Re: [madskristensen/TextmateBundleInstaller] Missing support for .sqlce files (#67)

 

Closed #67 <https://github.com/madskristensen/TextmateBundleInstaller/issues/67>  via  <https://github.com/madskristensen/TextmateBundleInstaller/commit/eab9cc89e6b95ae7215f20cb204704d7429d4c1c> eab9cc8.
