### ISSUE TITLE
Missing support for .tfignore files

### ISSUE THREAD

**Issue by HolisticDeveloper** [madskristensen/TextmateBundleInstaller#69]
[https://www.visualstudio.com/en-us/docs/tfvc/add-files-server#customize-which-files-are-ignored-by-version-control]()

Note, in the **.tfignore file rules** section of this page, some characters are improperly escaped when they should not be. This includes the `\#` in the first bullet, the `\*` in the second bullet, and the `\\` in the third bullet. See the [VS 2012 version](https://msdn.microsoft.com/en-us/library/ms245454(v=vs.110).aspx) of the page for reference. (Unfortunately the link to the specific section doesn't work in that version.)

**Comment by madskristensen** [comment]
I can't find any textmate bundles for .ignore files. Have you tried this extension? https://visualstudiogallery.msdn.microsoft.com/d0eba56d-603b-45ab-a680-edfda585f7f3

**Comment by HolisticDeveloper** [comment]
Thanks for the pointer to the **.ignore** extension, it works great. I only opened the issue here because when I opened the .tfignore file, there was a notice telling me I could right-click in the editor to report the missing support, like this one.

    ---------------------------
    Microsoft Visual Studio
    ---------------------------
    Syntax Highlighting Pack

    You can report missing language support for .tfignore and other files not currently supported by Visual studio by right-clicking inside the editor
    ---------------------------
    OK   
    ---------------------------

After clicking OK, I did not get an alert from the Suggested Extensions extension, so I went ahead and submitted this issue. However, I think I've figured out the problem with Suggested Extensions, so I'll open a separate issue for that.

**Comment by madskristensen** [comment]
Cool Thanks

**Comment by HolisticDeveloper** [comment]
madskristensen/SolutionExtensions#20
