### ISSUE TITLE
Protobuf - no syntax highlight for block comments

### ISSUE THREAD

**Issue by vassilvk** [madskristensen/TextmateBundleInstaller#71]
### Installed product versions
- Visual Studio: 2015 Professional - Update 3
- This extension: 2.3.0.46

### Description
Block comments are not highlighted in Protobuf files.

### Steps to recreate
1. Create a new `.proto` file.
2. Add the following code to it:
```
syntax = "proto3";
package MyPackage;

// Line comment.
message SampleRequest {
  /**
  A simple message string sent with the request.
  This message will be returned back to us with the SampleResponse.
  */
  string message = 1;
}
```

### Current behavior
Line comment on line 4 is highlighted as expected, however, block comment starting at line 6 is not.

### Expected behavior
Block comment should be highlighted as they are accepted and correctly processed by the Protobuf compiler.

**Comment by madskristensen** [comment]
Please open the issue on the textmate bundle repro for protobuf instead https://github.com/michaeledgar/protobuf-tmbundle
