### ISSUE TITLE
Missing support for .wax files

### ISSUE THREAD

**Issue by wstaelens** [madskristensen/TextmateBundleInstaller#79]
.wax files are for WiX (WiX Toolset) to create setups.
http://wixtoolset.org/

**Comment by madskristensen** [comment]
Doesn't this open in the XML editor already?

**Comment by wstaelens** [comment]
I guess not... otherwise I would have seen syntax highlighting on the xml, no?
That was my first guess that it was just xml and it should just "work".

**Comment by madskristensen** [comment]
Can you paste in example content of a .wax file, please? I can't seem to find any example online

**Comment by wstaelens** [comment]
it seems to open with the json editor (default) in VS2015update3.

```
<?xml version="1.0" encoding="utf-16"?>
<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DeployedProjects>
    <string>foo.csproj</string>
    <string>bar\foobar.csproj</string>
  </DeployedProjects>
  <DirectoryMappings>
    <Item Key="" Value="INSTALLFOLDER" />
  </DirectoryMappings>
  <FileMappings />
  <DeploySymbols>false</DeploySymbols>
</Configuration>`
