### ISSUE TITLE
Missing support for .elm files

### ISSUE THREAD

**Issue by bdukes** [madskristensen/TextmateBundleInstaller#82]
There's an existing TextMate/Sublime bundle at https://github.com/elm-community/Elm.tmLanguage/

I tried just adding that repo to my `~/.vs/Extensions/` folder, but it was deleted when VS started up (it worked if I added it while VS was running, but was gone on the next run).  Is it possible that this extension deleted that language/bundle?

**Comment by madskristensen** [comment]
You need to disable this extension while working in the `~/.vs/Extensions/` folder. That's what causes it to be deleted

**Comment by madskristensen** [comment]
I'm adding it right now to the extension

**Comment by madskristensen** [comment]
Try out the latest [CI build](http://vsixgallery.com/extension/4773ce75-6f30-4269-9557-1f7c30a47be2/) for Elm support

**Comment by bdukes** [comment]
👍 awesome, thanks so much for the quick turnaround, @madskristensen!
