### ISSUE TITLE
Missing support for .pug files

### ISSUE THREAD

**Issue by dpaquette** [madskristensen/TextmateBundleInstaller#87]
I don't get syntax highlighting for Pug files. It seems to work with the .jade extension but not for the .pug extension

**Comment by stimms** [comment]
There is a commit 2 months ago which claims to add it https://github.com/madskristensen/TextmateBundleInstaller/commit/6ef59fca7f974e4a0a13c2f0ff1e0efbd52bd7a8 should have been in 1.3

![image](https://cloud.githubusercontent.com/assets/153912/20193541/3afd6800-a743-11e6-84dd-5a21626ddf32.png)

**Comment by dpaquette** [comment]
This started working for me....must have been something with my machine
