### ISSUE TITLE
Missing support for .vdproj files

### ISSUE THREAD

**Issue by poduvalvishal** [madskristensen/TextmateBundleInstaller#92]
Optionally, please give more details such as language name and homepage URL

**Comment by madskristensen** [comment]
I thought .vdproj files were deprecated years ago with no support in VS2015 at all? As far as I can tell, it's sort of a JSON syntax, right? I can't find any Textmate bundles for it. Do you know of any?

**Comment by madskristensen** [comment]
Closed due to inactivity
